server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3396/db_hotel_clientes?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.upeu.hotel.cliente: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: 1s3alJJATsWK91vf5zrODYlQa+LauM/9udaLZlQhHlpu46g/KzmSS5c3CGy6xF9kzAqBhvjmKBuZO/pSL7tfOg==
  issuer: auth
