server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://${TIPO_HABITACION_DB_HOST:mysql-tipo}:${TIPO_HABITACION_DB_PORT:3306}/${TIPO_HABITACION_DB_NAME:db_hotel_tipos}?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: ${TIPO_HABITACION_DB_USERNAME:root}
    password: ${TIPO_HABITACION_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://registry-server:7081/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

jwt:
  secret: ${JWT_SECRET}
  issuer: auth
