name: tipo-habitacion-dev

services:
  mysql-tipo-habitacion-dev:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_hotel_tipos
    ports:
      - "3381:3306" # Tu máquina (cliente externo) → MySQL dev	
    volumes:
      - mysql_hotel_tipos_dev_data:/var/lib/mysql

volumes:
  mysql_hotel_tipos_dev_data: