name: observability-platform-dev

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "19090:9090"
    volumes:
      - ./prometheus/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - obs-dev-net

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    restart: unless-stopped
    ports:
      - "13100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    networks:
      - obs-dev-net

  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - ../infra/gateway/logs:/var/log/ms/gateway:ro
      - ../services/tipo-habitacion/logs:/var/log/ms/tipo-habitacion:ro
      - ../services/habitacion/logs:/var/log/ms/habitacion:ro
      - ../services/auth/logs:/var/log/ms/auth:ro
      - ../services/reserva/logs:/var/log/ms/reserva:ro
      - ../services/facturacion/logs:/var/log/ms/facturacion:ro
      - ../services/reportes/logs:/var/log/ms/reportes:ro
      - ../services/cliente/logs:/var/log/ms/cliente:ro
    depends_on:
      - loki
    networks:
      - obs-dev-net

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "13000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - obs-dev-net

volumes:
  prometheus_data:
  loki_data:
  grafana_data:

networks:
  obs-dev-net:
    name: obs-dev-net
